### PR TITLE
Re fix select behavior

### LINKED ISSUE #129: Select "fix" introduced new bug with option index ordering.
If a `select` looks like this after the "please select" processor checks it out...

* `select`
  * `option` "Please select..."
  * `option` Pie
  * `option` Ice Cream

If you select "Pie", the "Please select" option disappears, "Ice Cream" *appears* to be selected, but it's not actually selected. The issue is, adding a "please select" option is dependent on no other options being `selected`, so it disappears as soon as it's interacted with. So I think I'll need to revisit the `indexOffset` I set up.

### PR DESCRIPTION
**Pull request by ctcleary**
I basically just took the behavior I previously coded at the `types/select.js` level and moved it up to the `schema-edit/parse-schema.js` level, because we already know at the schema level whether we have a default value or not. This simplifies things a lot, with the only downside being the "Please select an option..." is now permanent, but that seems like a minor trade-off to me. 

[ Fixes #129 ]

### CODE REVIEW

File: src/pages/schema-edit/parse-schema.js [hunk 1]
```diff
@@ -31,6 +31,21 @@ function processSections(sections) {
     });
 }
 
+function processSelected(children) {
+    var hasSelected = children.find((option) => option.selected);
```
Comment (tivac) [inline src/pages/schema-edit/parse-schema.js]: This was dumb of me not to note earlier, but this project isn't being transpiled atm. This should be replaced w/ something not using Array.prototype.find and without the arrow function.

Or we could investigate how much time transpiling w/ buble would add, I'm not opposed to it.

**Comment by tivac** [comment]
Aside from the ES2015 bit this looks smart, thanks.

**Comment by ctcleary** [comment]
I hereby suggest that every time we have to do something like this, the verb to be used is "oldify."

**Comment by tivac** [comment]
Build failing due to ESLint issues, but neither are serious so will tweak after it lands. Thanks!

**Comment by ctcleary** [comment]
That's weird, I don't think I saw any on my local ST3.
